### ISSUE TITLE
Doing 404 error return to login page

### ISSUE THREAD

**Issue by Predeactor** [NeuroAssassin/Red-Dashboard#2]
# Steps to reproduce

1. Start the Red Dashboard.
2. Go to your dashboard (Tested with bot RPC server connected).
3. Write anything you want at the end of the URL.

# Expected 

Getting redirected to a well made 404 page.

# Happens

We're getting redirected to the login page.

**Comment by Predeactor** [comment]
Fixed locally by @NeuroAssassin.

**Comment by NeuroAssassin** [comment]
Should now be officially fixed in v0.1.4a.  Closing.
